---
- hosts: localhost
  vars:
    puppet_agent_version: 1.8.2
  tasks:
    - name: clone puppet agent
      git:
        repo: https://github.com/puppetlabs/puppet-agent.git
        dest: "{{ playbook_dir }}/puppet-agent"
        update: no
        version: "{{ puppet_agent_version }}"

    - name: clone vanagon
      git:
        repo: https://github.com/puppetlabs/vanagon.git
        dest: "{{ playbook_dir }}/puppet-agent/vanagon"
        update: no
        version: 0.8.2

    - name: patch vanagon rpm platform
      patch:
        src: "patches/{{ puppet_agent_version }}/puppet-agent/vanagon/lib/vanagon/platform/rpm.rb.patch"
        dest: "{{ playbook_dir }}/puppet-agent/vanagon/lib/vanagon/platform/rpm.rb"

    - name: patch puppet-agent project
      patch:
        src: "patches/{{ puppet_agent_version }}/puppet-agent/configs/projects/puppet-agent.rb.patch"
        dest: "{{ playbook_dir }}/puppet-agent/configs/projects/puppet-agent.rb"

    # i386x
    - name: patch el-5-i386 platform
      patch:
        src: "patches/{{ puppet_agent_version }}/puppet-agent/configs/platforms/el-5-i386.rb.patch"
        dest: "{{ playbook_dir }}/puppet-agent/configs/platforms/el-5-i386.rb"

    # x86_64
    - name: patch el-5-x86_64 platform
      patch:
        src: "patches/{{ puppet_agent_version }}/puppet-agent/configs/platforms/el-5-x86_64.rb.patch"
        dest: "{{ playbook_dir }}/puppet-agent/configs/platforms/el-5-x86_64.rb"

    - name: patch el-7-x86_64 platform
      patch:
        src: "patches/{{ puppet_agent_version }}/puppet-agent/configs/platforms/el-7-x86_64.rb.patch"
        dest: "{{ playbook_dir }}/puppet-agent/configs/platforms/el-7-x86_64.rb"

    # s390x
    - name: patch el-6-s390x platform
      patch:
        src: "patches/{{ puppet_agent_version }}/puppet-agent/configs/platforms/el-6-s390x.rb.patch"
        dest: "{{ playbook_dir }}/puppet-agent/configs/platforms/el-6-s390x.rb"

    - name: patch el-7-s390x platform
      patch:
        src: "patches/{{ puppet_agent_version }}/puppet-agent/configs/platforms/el-7-s390x.rb.patch"
        dest: "{{ playbook_dir }}/puppet-agent/configs/platforms/el-7-s390x.rb"

    # ppc64
    - name: copy el-6-ppc64.rb platform
      copy:
        src: newfiles/puppet-agent/configs/platforms/el-6-ppc64.rb
        dest: "{{ playbook_dir }}/puppet-agent/configs/platforms/el-6-ppc64.rb"

    - name: copy el-7-ppc64.rb platform
      copy:
        src: newfiles/puppet-agent/configs/platforms/el-7-ppc64.rb
        dest: "{{ playbook_dir }}/puppet-agent/configs/platforms/el-7-ppc64.rb"

    # components
    - name: patch ruby-selinux component
      patch:
        src: "patches/{{ puppet_agent_version }}/puppet-agent/configs/components/ruby-selinux.rb.patch"
        dest: "{{ playbook_dir }}/puppet-agent/configs/components/ruby-selinux.rb"

    - name: patch leatherman component
      patch:
        src: "patches/{{ puppet_agent_version }}/puppet-agent/configs/components/leatherman.rb.patch"
        dest: "{{ playbook_dir }}/puppet-agent/configs/components/leatherman.rb"

    - name: patch cpp-hocon component
      patch:
        src: "patches/{{ puppet_agent_version }}/puppet-agent/configs/components/cpp-hocon.rb.patch"
        dest: "{{ playbook_dir }}/puppet-agent/configs/components/cpp-hocon.rb"

    - name: patch cpp-pcp-client component
      patch:
        src: "patches/{{ puppet_agent_version }}/puppet-agent/configs/components/cpp-pcp-client.rb.patch"
        dest: "{{ playbook_dir }}/puppet-agent/configs/components/cpp-pcp-client.rb"

    - name: patch facter component
      patch:
        src: "patches/{{ puppet_agent_version }}/puppet-agent/configs/components/facter.rb.patch"
        dest: "{{ playbook_dir }}/puppet-agent/configs/components/facter.rb"

    - name: patch ruby-augeas component
      patch:
        src: "patches/{{ puppet_agent_version }}/puppet-agent/configs/components/ruby-augeas.rb.patch"
        dest: "{{ playbook_dir }}/puppet-agent/configs/components/ruby-augeas.rb"

    - name: patch ruby-shadow component
      patch:
        src: "patches/{{ puppet_agent_version }}/puppet-agent/configs/components/ruby-shadow.rb.patch"
        dest: "{{ playbook_dir }}/puppet-agent/configs/components/ruby-shadow.rb"

    - name: patch rubygem-locale component
      patch:
        src: "patches/{{ puppet_agent_version }}/puppet-agent/configs/components/rubygem-locale.rb.patch"
        dest: "{{ playbook_dir }}/puppet-agent/configs/components/rubygem-locale.rb"

    - name: puppet-agent dir bundle update
      shell: "/bin/bash --login -c 'source ~/.rvm/scripts/rvm && rvm_is_not_a_function=0 rvm use 2.2.1@puppet-agent-build && VANAGON_LOCATION=file://{{ playbook_dir }}/puppet-agent/vanagon bundle update'"
      args:
        chdir: "{{ playbook_dir }}/puppet-agent"
        creates: Gemfile.lock

    - name: vanagon dir bundle update
      shell: "/bin/bash --login -c 'source ~/.rvm/scripts/rvm && rvm_is_not_a_function=0 rvm use 2.2.1@puppet-agent-build && VANAGON_LOCATION=file://{{ playbook_dir }}/puppet-agent/vanagon bundle update'"
      args:
        chdir: "{{ playbook_dir }}/puppet-agent/vanagon"
        creates: Gemfile.lock

    - name: build puppet-agent
      shell: "/bin/bash --login -c 'source ~/.rvm/scripts/rvm && rvm_is_not_a_function=0 rvm use 2.2.1@puppet-agent-build && VANAGON_SSH_KEY=~/.ssh/id_rsa VANAGON_RETRY_COUNT=3 VANAGON_LOCATION=file://{{ playbook_dir }}/puppet-agent/vanagon bundle exec build puppet-agent el-{{ hostvars[item]['el_version'] }}-{{ hostvars[item]['el_arch'] }} {{ item }}'"
      args:
        chdir: "{{ playbook_dir }}/puppet-agent"
      with_items: "{{ groups['build_host'] }}"


- hosts: build_host
  become: true
  tasks:
    - name: find srpm
      shell: find /var/tmp | grep "src.rpm$"
      register: srpm_path

    - name: create arch destination directory
      file:
        dest: "{{ playbook_dir }}/rpms/{{ el_arch }}"
        state: directory

    - name: get srpm from host
      fetch:
        src: "{{ item }}"
        dest: "{{ playbook_dir }}/rpms/{{ el_arch }}/"
        flat: yes
      with_items: "{{ srpm_path.stdout.split('\n') }}"
